index:
   path: /
   controller: App\Controller\DefaultController::index

redirecthomepage:
   path: /homepage
   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
   defaults:
      route: 'blog_homepage'
      permanent: true
      keepQueryParams: true

cgu:
   path: /cgu
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
   defaults: 
      template: cgu.html.twig